version: '3'
services:
  rws:
    image: "loqutus/rws"
    ports:
      - "8888:8888"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/hostname:/etc/hostname"
      - "/data:/Users/rusik/gopath/src/github.com/loqutus/rws/test/data"