version: '3'
services:
  rws:
    image: "rws-local"
    ports:
      - "8888:8888"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/rusik/go/src/github.com/loqutus/rws/test/data:/data"
  etcd:
    image: "bitnami/etcd"
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes