version: '3'
services:
  rws:
    image: "loqutus/rws"
    ports:
      - "8888:8888"
    volumes:
      - "/etc/hosts:/etc/hosts"
      - "/etc/nsswitch.conf:/etc/nsswitch.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data:/home/rusik/go/src/github.com/loqutus/rws/test/data"
      - "/etc/hostname:/etc/hostname"
